### ISSUE TITLE
Consider adding a hash to the definition data

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#261]
To add rigor and increase confidence, it might be useful to have a hash of each file and perhaps the whole package. need to settle on a hash algorithm. Ideally it would line up with Software Heritage's approach (which IIRC emphasizes Git compatibility)

**Comment by zacchiro** [comment]
Here is, for your consideration, the full spec of Software Heritage persistent identifiers (PID): https://docs.softwareheritage.org/devel/swh-model/persistent-identifiers.html

They support identifying several different source code "artifacts", such as: file contents, directories, commits, releases, up to snapshots that capture the full state of a repository (i.e., where each branch/tag points at the time the snapshot is taken).

As @jeffmcaffer mentioned they are indeed compatible with Git identifiers (with the exception of snapshots, because they do not exist in the Git data model). Note, however, that Git-compatibility is not by design, it's just for convenience given the popularity of Git. (That said, we do not foresee changing that anytime soon.)

It is also worth pointing out that Git itself has started the process of migrating from SHA1-based checksums to SHA256-based ones. We will most likely follow the same path, and our PIDs are versioned, so we do not expect major problems. But you *should* think about how to deal with that migration the day it will happen, especially if you have Git-compatibility as an explicit goal.

I'm happy to answer additional questions here if you have any.
Hope this helps,

**Comment by dabutvin** [comment]
we are now hashing every file with sha-1 and sha-256 as well as the artifact itself before decompressing
