### ISSUE TITLE
Merging licenses should union

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#383]
There are cases where one tool finds a license that another does not. Since aggregation is done in a layered "precedence" ordering, it is possible for that extra license to be overwritten by a higher precedence tool. In general we don't really want precedence but have to make a choice. Here we can merge the license lists.

In particular, in utils.js

```js
function _mergeLicense(base, proposed) {
  return !proposed || proposed === 'NOASSERTION' ? base : proposed
}
```

should be enhanced to start with the base and add in the proposed licenses only if they are not already satisfied by the base. There are probably some edge cases and interesting questions but it should be doable/deterministic.

An example of this scenario https://clearlydefined.io/definitions/npm/npmjs/@angular/compiler/6.1.10
The following files have Apache in them but show as only MIT. ScanCode discovers Apache but only with a score of 74 (below the threshold of 80) and so is ignored. Nomos sees both but because ScanCode is higher precedence, that value is ignored.

* bundles/compiler-testing.umd.js
* bundles/compiler-testing.umd.js.map
* bundles/compiler-testing.umd.min.js.map
* bundles/compiler.umd.js
* bundles/compiler.umd.js.map
* bundles/compiler.umd.min.js.map

**Comment by OliverFendt** [comment]
this is great because the data provided for @angular/common/6.1.10 lack the same information.
the files:

- bundles/common-http-testing.umd.js
- bundles/common-http-testing.umd.js.map
- bundles/common-http-testing.umd.min.js.map
- bundles/common-http.umd.js
- bundles/common-http.umd.js.map
- bundles/common-http.umd.min.js.map
- bundles/common-testing.umd.js
- bundles/common-testing.umd.js.map
- bundles/common-testing.umd.min.js.map
- bundles/common.umd.js
- bundles/common.umd.js.map
- bundles/common.umd.min.js.map
contain the information that they are licensed und MIT and below this you also find the reference to the Apache-2.0 
The same applies to other angular packages.
