### ISSUE TITLE
[NPM] use licenses array if there is only a single entry

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/service#458]
we ignore `licenses` property today, primarily because if there are 2 licenses we don't know if they AND or OR together, but if there is one we can use it, so let's.

ex:

do nothing:
```json
{ "licenses" :
  [
    { "type": "MIT"
    , "url": "https://www.opensource.org/licenses/mit-license.php"
    }
  , { "type": "Apache-2.0"
    , "url": "https://opensource.org/licenses/apache2.0.php"
    }
  ]
}
```

parse it out:
```json
  "licenses": [
    {
      "type": "MIT",
      "url": "http://github.com/mscdex/ssh2-streams/raw/master/LICENSE"
    }
  ],
```

**Comment by dabutvin** [comment]
update the summarizer here: https://github.com/clearlydefined/service/blob/master/providers/summary/clearlydefined.js#L239-L242

update the tests here:

https://github.com/clearlydefined/service/blob/master/test/summary/clearlyDefined.js#L232-L237

**Comment by geneh** [comment]
Other examples:
https://clearlydefined.io/definitions/npm/npmjs/-/grunt-contrib-concat/0.5.1
https://clearlydefined.io/definitions/npm/npmjs/-/faye-websocket/0.4.4

**Comment by tmarble** [comment]
Back with commit c0c8d8c6272b52779e7cf2c6fc4c4b353b374dae Fredrick changed licensing processing from handling a string to _only_ handing array by combining terms disjunctively (`OR`).

And it turns out there is _only_ test coverage for the array case, not if license is simple string:
https://github.com/clearlydefined/service/blob/master/test/summary/clearlydefinedTests.js#L136-L151

Therefore this bug will pivot to adding handing for both license as string and array as well as adding test coverage for license as a string.

**Comment by geneh** [comment]
That change was related to composer type. This issue is related to npm type.

**Comment by geneh** [comment]
@ariel11 Could you please confirm if there is an array of licenses, it cannot be determined whether they should be joined with OR or AND?

**Comment by tmarble** [comment]
@geneh @ariel11 for what it's worth the example schema given by the current version of NPM
at https://docs.npmjs.com/files/package.json#license only refers to `OR` based on the examples.

I actually have never seen a license *conjunction*? Have any open source lawyers publically commented on the approach here? Does anyone have *any* examples of "License-A AND License-B" in the wild?

**Comment by tmarble** [comment]
And I will point you to Fredrick's commit above where the combination (in the case Composer packages) is assumed to be `OR`. And the Composer schema is explicit about this:
https://getcomposer.org/doc/04-schema.md#license

**Comment by tmarble** [comment]
I want to thank @pombredanne  for helping me understand this better!
Philippe references the way scancode processes Composer and NPM declarations.
1. Composer defaults to OR
  - We see here in [scancode](https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/phpcomposer.py#L130) that Composer defaults to OR (agrees with the schema statement above)
2. NPM should default to AND
  - Philippe's argument is that if the operator is not explictly given, we should choose AND which is the most restrictive (a Clearly Defined user could later specify OR if the intent is indeed disjunctive).
 - I agree this is better behavior than not setting the license at all because it's much easier to switch AND to OR (than to re-create the SPDX expression from scratch).
  - Here's the example of where [scancode reads an NPM license array](https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/npm.py#L151) -- without a relation operator -- which [defaults to AND](https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/utils.py#L153)

If you agree with this reasoning, @ariel11, I will amend the PR to match this understanding.

Please advise!

**Comment by tmarble** [comment]
In the curation call today there was consensus with @ariel11 @pombredanne @royaljust and @SharonCorbett that the default should be `AND`.

There was also agreement that during curation it is usually quite clear if a "dual" (disjunctive) license is intended through language like "at your choice you may select License-A or License-B" or the programmer style expression `{ License-A | License-B }` (i.e. the [pipe symbol](https://www.fileformat.info/info/unicode/char/7c/index.htm))

**Comment by geneh** [comment]
The affected npm & packagist definitions with an array of license/s need to be recomputed to improve declared licenses detection corrected in https://github.com/clearlydefined/service/pull/679. I'll close this issue once it's done.

**Comment by tmarble** [comment]
@geneh I'm not super clear on the next action here. Since you assigned it to yourself does that mean you are going to do it? If not could explain in little bit more detail what needs to be done?

**Comment by geneh** [comment]
@tmarble Yes, I'll do it. Basically, all the newly crawled definitions are going to be automatically addressed by this change but not the existing ones. In order to save curators a lot of manual work I am going to write a script to find the affected definitions and make sure they are recomputed.

**Comment by tmarble** [comment]
@geneh cool! that makes sense!

**Comment by geneh** [comment]
@tmarble The following use case still hasn't been addressed for npm:
```
        "licenses": [
          {
            "type": "MIT",
            "url": "http://github.com/wearefractal/4chanjs/raw/master/LICENSE"
          }
        ]
```
Example: https://clearlydefined.io/definitions/npm/npmjs/-/4chanjs/0.0.1

**Comment by geneh** [comment]
Need to recompute NPM definitions with multiple declared licenses in package.json.
I'll close the issue when done.

**Comment by geneh** [comment]
Done! npm NOASSERTION rate has decreased by more than 1%.
