### ISSUE TITLE
Sort by newer doesn't sort by newer release date

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/service#465]
As mentioned in https://github.com/clearlydefined/website/issues/635 , sorting by releaseDate , sortDesc=true , returns some wrong ordered data.

See attached screenshots:

![Screen Shot 2019-03-28 at 7 54 37 AM](https://user-images.githubusercontent.com/17101092/55167801-e000b900-512e-11e9-9f0d-cd2bf318a215.png)

![Schermata 2019-03-29 alle 09 44 19](https://user-images.githubusercontent.com/7654979/55220332-54a72680-5207-11e9-98fa-ac877cfefa07.png)

**Comment by storrisi** [comment]
I've also noticed that some definitions has a releaseDate in the future, like: releaseDate: "2025-06-04" or releaseDate: "2031-01-09".

**Comment by jeffmendoza** [comment]
Also see #464

**Comment by nellshamrell** [comment]
The search UI appears to have significantly changed since this was filed. Doing a spot check of a search in both the UI and in an API call, this appears to now be working as expected.

![image](https://user-images.githubusercontent.com/813007/103941368-96a31300-50e3-11eb-9ea9-0c2fd298b80a.png)

Closing, but if anyone sees this bug again please feel free to re-open.
