### ISSUE TITLE
declared license merging off

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#469]
From @kevinsawicki
Was just curious to get more details on what declared  a license of GPL-2.0-only AND Ruby OR GPL-2.0-only denotes, seen on https://clearlydefined.io/definitions/gem/rubygems/-/soap4r-spox/1.6.0 like how to parse the and/or when GPL-2.0-only appears in both

**Comment by jeffmcaffer** [comment]
Hmmm, that one looks odd. The RUBYS file has both the Ruby license and the GPL license with `OR` terminology. there is likely  (I didn't find it in my quick look)  another indication that the license is different and then when those results are merged, they are not being reduced properly.

**Comment by fossygirl** [comment]
I recently noticed https://github.com/clearlydefined/service/issues/461 as well. May be related, may not be.

**Comment by pombredanne** [comment]
let me also check in this on the ScanCode side. But from a quick glance I think this is because there are several top level files with licenses so basically:
 - `GPL-2.0-only` should come from the GPL file
-  `Ruby OR GPL-2.0-only` should come from the RUBYS file from the ScanCode scan
- there are other correct but short detection of the RUBY license in the COPYING file but this not kept because of the lower score
- there are no other license information in the top level, key files (e.g. no README, no gemspec license)

Then all these would be concatenated in an expression which is  `GPL-2.0-only AND Ruby OR GPL-2.0-only` and become the declared license since there is no easy way to determine automatically that the presence of a top level GPL full text may in fact be because of the Ruby or GPL choice. 

I would need to check if this happens in ScanCode or in the CD code... but in anycase it seems "correct" to me be albeit surprising.

**Comment by ignacionr** [comment]
The word patching occurs at the CD service, but as stated by @pombredanne even if it looks odd it seems about the best automated tools can say.
My suggestion is that Philippe's explanation for this particular case is valid, and that we should give the OP the idea that information provided by packages can seem (or even be) contradictory at times.
