### ISSUE TITLE
some declared licenses are not sorted

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#499]
If you look at https://clearlydefined.io/definitions/crate/cratesio/-/crossbeam-epoch/0.6.0, the declared license is showing at MIT OR Apache-2.0. It should be Apache 2.0 OR MIT (sorted alphabetically). 

There must be some place in the code that `spdx.merge` is not being called. Specifically the functionality in `_stringifyOrAnds` is not being called.

@dabutvin and I looked at this for a while and found some fixes but I think there is still an issue around cases where one of the `merge` arguments is falsey. In that case the other arg is returned in its raw form. While this is technically correct, it seems inconsistent. We'd end up with the licenses in an AND expression sometimes sorted and sometimes not.

**Comment by dabutvin** [comment]
let's verify if this was fixed in #498

**Comment by dabutvin** [comment]
this was fixed in #498 !
https://dev.clearlydefined.io/definitions/crate/cratesio/-/crossbeam-epoch/0.6.0 is correct now.
We are now appropriately applying the 'AND' as well !!

We just need to recompute the definitions for the affected components.
I'll pro-actively recompute a batch now, the rest will catch up eventually
