### ISSUE TITLE
Files paths containing characters gets duplicated

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/service#534]
See https://dev-api.clearlydefined.io/definitions/nuget/nuget/-/Newtonsoft.Json/10.0.2?expand=prs

The returned files property contains duplicated file paths, due a wrong management of the '+' character:

<img width="753" alt="Schermata 2019-05-22 alle 13 58 31" src="https://user-images.githubusercontent.com/7654979/58172850-0445c580-7c9a-11e9-9b06-0d45bec49000.png">

Line 18 and 19 are actually the same of 23 and 24

**Comment by ignacionr** [comment]
# Implementation Notes

## Findings
The incorporation of NuGet package files got merged at https://github.com/clearlydefined/service/pull/294 which took as an example that very package (Newtonsoft Json). In order to make the browsing experience cleaner, the original contents of the files get decoded -as seen at https://github.com/clearlydefined/service/commit/6753b2992c3022d55d07d444cf30d68638fa7823#diff-ce695010654b51226ce5cde1a403ab48R111 ; now, the list of files then get 'merged' with the existing definition, which is permeable of the duplication we find.

## Proposals
Decide on one of the following.

- Leave the files un-decoded. The actual zip file on NuGet, has the names encoded. It is likely that other tools will not decode those names. Thus, preserving the file name should help preserve its identity.
- Make it so merge works smarter, and tries to find dups by applying a few rules before doing the actual merge. One of such rules can be decoding uri chars.
- Create a separate procedure that generally de-duplicates files found in packages, applying a set of rules including the decoding/encoding of url components.

**Comment by ignacionr** [comment]
@dabutvin what are your thoughts?

**Comment by ignacionr** [comment]
Just to explain more clearly, I manually downloaded the compressed file, and checked that the entries in there look url-encoded; so decoding them was simply erroneous (the decoded file names won't work on the package).
