### ISSUE TITLE
Add clearlydefined link in bot curations

### ISSUE THREAD

**Issue by royaljust** [clearlydefined/service#540]
When the clearlydefined bot makes a curation having a link to the component in ClearlyDefined included in the PR would make review of the curation community faster.

**Comment by royaljust** [comment]
> Are you suggesting to add a direct link to every element shown in the list of "Affected definitions:" ?

@storrisi - exactly.  That would be very helpful.

**Comment by geneh** [comment]
Please make the hostname to be either https://clearlydefined.io or https://dev.clearlydefined.io based on the environment.
https://github.com/clearlydefined/service/blob/master/providers/curation/github.js#L264
`}](https://clearlydefined.io/definitions/${EntityCoordinates.fromObject(def.coordinates)}/${`

**Comment by storrisi** [comment]
@geneh looks like we don't have such kind of information about the actual environment, probably we should add a new environment attribute in the env.json file.
BTW, i'm not sure about the purpose of this change, since the curation will be always in production, there's no other case where the url could be different from clearlydefined.io .

The development environment is used only for testing purposes , so probably we don't really need to have a different url?

**Comment by geneh** [comment]
Okay, let's leave it this way for now.
