### ISSUE TITLE
Include linked-to license information in NuGet harvesting.

### ISSUE THREAD

**Issue by royaljust** [clearlydefined/service#636]
The project has many NuGet files that have "noassertion" as a declared license.  However, for many of these, the NuSpec will have a "licenseUrl" tag that provides a clear link to license information.  Harvesting the text at that link and running it through tooling will likely decrease the manual review required across the NuGet ecosystem significantly.

![image](https://user-images.githubusercontent.com/36014796/66506803-07e8b600-ea9c-11e9-9bd5-9fb15d37f8eb.png)

**Comment by geneh** [comment]
This issue is now resolved for nuget/nuget/-/Microsoft.AspNetCore.Authentication/2.2.0:
https://clearlydefined.io/definitions/nuget/nuget/-/Microsoft.AspNetCore.Authentication/2.2.0
https://dev.clearlydefined.io/definitions/nuget/nuget/-/Microsoft.AspNetCore.Authentication/2.2.0
The declared license is Apache-2.0 based on licenseUrl.

I am going to check the data to see if other NuGet license URL patterns can be detected in a similar manner.

**Comment by royaljust** [comment]
Thanks for the continued work here @geneh - looking beyond URL patterns will be very helpful for situations where the NuGet package has a link that goes back to a GitHub or other repository top level license file.

**Comment by geneh** [comment]
@royaljust Do you mean it should be helpful to make the contents of the file available for the tools to crawl?

**Comment by geneh** [comment]
PR https://github.com/clearlydefined/service/issues/636 should increase declared license detection by 70% / 113,306 from 159,946 once the affected components' definitions are refreshed.
