### ISSUE TITLE
HTTP error 403 when downloading Swagger schema

### ISSUE THREAD

**Issue by sschuberth** [clearlydefined/service#651]
I'm trying to download https://api.clearlydefined.io/schemas/swagger.yaml via Kotlin code as [part of a build process](https://github.com/heremaps/oss-review-toolkit/blob/55c729a43882168eb010c3cc329b53a75e0108ae/clearly-defined/build.gradle.kts#L13). Interestingly, this gives:

```
FAILURE: Build failed with an exception.

* Where:
Build file 'oss-review-toolkit/clearly-defined/build.gradle.kts' line: 13

* What went wrong:
Server returned HTTP response code: 403 for URL: https://api.clearlydefined.io/schemas/swagger.yaml

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.clearlydefined.io/schemas/swagger.yaml
        at kotlin.io.TextStreamsKt.readBytes(ReadWrite.kt:150)
        at Build_gradle$1.execute(build.gradle.kts:13)
        at Build_gradle$1.execute(build.gradle.kts:1)
```

From the same machine, a download via `curl` or `wget` works, so it does not seem to be a network issue on my side.

Is there something done on the server side that could cause this?

**Comment by ignacionr** [comment]
Thank you @sschuberth for this input. We use the services of a CDN (CloudFlare) in order to deliver contents fast and with some checks that allow for a healthy scalability.
Sometimes, CloudFlare will blacklist IPs on cloud services, because they have been historically used by hackers. This could be the case with an on-demand cloud service acquired at the time your build process starts.

In order to verify this, could you please gather the headers of the response? This will help us make sure that the response is from CloudFlare.

**Comment by sschuberth** [comment]
I'll try to gather the headers @ignacionr. But out of curiosity, if it's an IP issue, how do you explain that the download from the same machine via `curl` works, but not from within the build script?

**Comment by ignacionr** [comment]
Thanks again @sschuberth for following up. I (maybe incorrectly) assumed that you were running CI on the cloud (which normally allocates processing power and networking on the fly). Actually if you have tested from the exact same IP (kindly record that IP address), then your issue might be a lot simpler.
You see, curl creates correct and complete request headers; it might be the case that the client you have created/used does not provide such headers by default. Then once again, the CDN would possibly block a request that isn't recognized as a known browser.
But this is all hypothetical, and in any case it's only trying to help you find out what the problem is (as you confirm, curl, Safari, Chrome, and all our supported clients are able to fetch the resource with no issues or warnings of any kind).
Your input with the response headers (and content) will help. If it proves difficult to gather those from your own code, you can always resort to a local debugging proxy such as [fiddler](https://www.telerik.com/fiddler). My endorsement of that tool is only at a personal level and to help you find the issue more quickly.

**Comment by ignacionr** [comment]
@sschuberth please share your response headers when you can, then reopen this issue if necessary. Thank you!

**Comment by jeffmcaffer** [comment]
This one is odd. I can cut and paste that URL into my browser and it works fine. @sschuberth are you still having the problem?

**Comment by sschuberth** [comment]
> This one is odd. I can cut and paste that URL into my browser and it works fine.

Same here. It's only an issue when using the URL from within a Gradle build script and trying to download from the URL via Java's [URL.openStream](https://docs.oracle.com/javase/8/docs/api/java/net/URL.html#openStream--) (via [Kotlin's readText() for URLs](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.net.-u-r-l/read-text.html)).

I'd be curious if either @ignacionr or @jeffmcaffer could reproduce this by checking out the *clearlydefined-issue-651* branch of https://github.com/heremaps/oss-review-toolkit and running

    ./gradlew :clearly-defined:openApiGenerate

See the file at `clearly-defined/build.gradle.kts` for the URLs and comments.

**Comment by sschuberth** [comment]
Update, I tried to reproduce the issue on another machine, but there my *clearlydefined-issue-651* branch does *not* fail to download the Swagger schema. On the machine where I can still reproduce the issue I have a rather complicated network setup: It's a VM that is running OpenVPN, and the host machine can only access the Internet via a proxy. I'll still try to get the HTTP headers, thought.

**Comment by sschuberth** [comment]
@ignacionr, the `GET` header looks like

    15:38:19.599 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@644cfa0c5 pairs: {GET /schemas/swagger.yaml HTTP/1.1: null}{User-Agent: Java/1.8.0_222}{Host: api.clearlydefined.io}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}

and the response header looks like:

    15:38:19.615 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@67abaa3312 pairs: {null: HTTP/1.1 403 Forbidden}{Date: Mon, 11 Nov 2019 14:38:19 GMT}{Content-Type: text/html; charset=UTF-8}{Transfer-Encoding: chunked}{Connection: keep-alive}{Set-Cookie: __cfduid=de7424e768c6105df0f13c03ebfd0c7d01573483099; expires=Tue, 10-Nov-20 14:38:19 GMT; path=/; domain=.clearlydefined.io; HttpOnly; Secure}{Cache-Control: max-age=10}{Expires: Mon, 11 Nov 2019 14:38:29 GMT}{X-Frame-Options: SAMEORIGIN}{Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"}{Server: cloudflare}{CF-RAY: 5341025c2df7d0fd-TXL}

**Comment by ignacionr** [comment]
You have a somewhat funny way of presenting headers, but the last few on the response do confirm that the issue is caught by CloudFlare as anticipated.
Please contact the “report url” for further tracking with them.

**Comment by ignacionr** [comment]
The issue is between the API consumer and CloudFlare, we indicate how to contact them and investigate. If anything requires our attention please reopen. Thank you.

**Comment by sschuberth** [comment]
> You have a somewhat funny way of presenting headers

FYI, that's not "my" way, but the standard way in which Java logs headers for `HttpURLConnection`.
