### ISSUE TITLE
Problems persist with harvest page GitHub fields; inconsistent recommendations returned

### ISSUE THREAD

**Issue by bduranc** [clearlydefined/service#661]
**Issue Type:** Bug
**Issue Description:**

An effort was made to resolve in #599, but there still appears to be some problems with the GitHub fields on the [harvesting page](https://clearlydefined.io/harvest). When you enter in distinct org names such as "_gnu_" or "_erica_", the results returned in the recommendations do not appear to be sorted and there's lots of noise. In the worst case, what you type does not even show up in the list at all.

See examples below:

Example A: org "_gnu_" **does not** show up in list.

<img width="253" alt="2019-11-08_10-53-29" src="https://user-images.githubusercontent.com/31491646/68452262-f1a75480-0217-11ea-919d-e05aaa06c560.png">

Example B: org "_erica_" shows up in list, but is not sorted to be at top.

<img width="216" alt="2019-11-08_10-55-23" src="https://user-images.githubusercontent.com/31491646/68452285-0f74b980-0218-11ea-9eb9-a32b9ae37b7d.png">

Example C: org "_kubernetes_" only shows if the letters "_e_" and "_s_" are removed at end.

<img width="219" alt="2019-11-08_10-53-42" src="https://user-images.githubusercontent.com/31491646/68452403-68445200-0218-11ea-9072-b1ad69f069ff.png">

<img width="209" alt="2019-11-08_10-54-50" src="https://user-images.githubusercontent.com/31491646/68452407-6b3f4280-0218-11ea-82c4-31834ff21242.png">

As a user, I'd naturally expect that if I enter "_gnu_" into the GH org field, that result would be at the very top. All fields that have the recommendations feature would probably work better this way. 

The more critical issue is when you cannot harvest something because it's org does not show up. 

The responses recorded from my browser are attached [here. (responses.txt)](https://github.com/clearlydefined/service/files/3823148/responses.txt)

**Browser:** Chrome 64-bit ver 78.0 on Windows

**Comment by ThomasHintz** [comment]
First, the reason 'gnu' doesn't work is because it is not an organization or user on github. If you try an actual organization like 'microsoft' it does work.

Second, the sort ordering can be changed from 'repositories' to the default 'best match' and that will fix the issue of an exact match not showing up first in the results. I think that is the best solution right now regardless since currently you could run in to a case where it is impossible to select the desired user/org even if you type it in as an exact match. We limit the search to 100 and sort by number of repos so if a user/org has a small number of repos and their user/org ID is a substring of many others with more repos they will never show up in the list. Using 'best match' sorting fixes that issue as well.
