### ISSUE TITLE
Curations not showing up

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#685]
It looks like https://github.com/clearlydefined/curated-data/pull/2895 was curating OTHER, however, it shows 0 "files changed" on the PR.  We are closing it. .  

A subsequent PR #2901 (https://github.com/clearlydefined/curated-data/pull/2901/files) changed OTHER to HPND, but this curation is not showing up in the declared license field.
 
The component - https://clearlydefined.io/definitions/pypi/pypi/-/pillow/6.2.1/6.2.1 - shows two PRs - #2901 and #2826 (it doesn’t show #2895). #2826 also curated OTHER (https://github.com/clearlydefined/curated-data/pull/2826/files) and was merged (later updated by #2901).
 
I don’t know why HPND is not showing up for the declared license, per https://github.com/clearlydefined/curated-data/pull/2901/files.

**Comment by geneh** [comment]
It looks like it may be a casing issue:
https://github.com/clearlydefined/curated-data/blob/master/curations/pypi/pypi/-/Pillow.yaml
https://github.com/clearlydefined/curated-data/blob/master/curations/pypi/pypi/-/pillow.yaml
It should be investigated how this component's curation can be corrected and how similar problems may be prevented in the future.

**Comment by ThomasHintz** [comment]
I couldn't figure out how to reproduce this using the webpage UI but I did discover that just changing the case in the URL and then curating would cause the issue. To me this means that the backend (both for serving the page and handling curations) needs to either 404 a package with the wrong case or otherwise respond with the correct one.

As far as correcting this instance I believe the fix would be to remove the yaml with the incorrect case and merge it into the one with the correct case.

**Comment by geneh** [comment]
Probably related to https://github.com/clearlydefined/service/issues/604

**Comment by ThomasHintz** [comment]
It seems like it could be related to #604. I think the issue is that changes made for matchCasing [here](https://github.com/clearlydefined/service/blob/e00127f80ff7fdc57605ff05d2b1d7c3bb8a9b18/routes/definitions.js#L75) never have any actual effect because they rely on the results of the definitionService which seems to always lower case the names that are used as keys. (see listAll, _getCacheKey) So the casingEnforced reduce in definitions.js will never actually filter anything out and my testing confirms this. Changing line 79 in definitions.js to `.keys(coordinatesList.map(x => x.toString()))` fixes the issue in my testing.

However, I wasn't actually able to pinpoint how this fits in to the flow of things or what might point to it that causes the issue. The web interface only seems to hit the preview endpoint. So how does the POST /definitions endpoint actually get triggered? If I find out or can figure out that this does indeed fit in to the curation process I'll go ahead and finish up a commit for it.

**Comment by pombredanne** [comment]
FWIW, note that  case does not matter in Python package names (as well as underscore vs. dash) so all these are the same:
- https://pypi.org/project/scancode-toolkit/
- https://pypi.org/project/ScanCode-Toolkit/
- https://pypi.org/project/ScanCode_Toolkit/
- https://pypi.org/project/scancode_toolkit/

This is how this is treated in Package URL https://github.com/package-url/purl-spec :

> `PyPi treats '-' and '_' as the same character and is not case sensitive. Therefore a Pypi package name must be lowercased and underscore '_' replaced with a dash '-'`

Pypi still keeps the original case as the default, but ignores case and dash/underscore as explained above.

**Comment by ThomasHintz** [comment]
AFAICT the curation process does not involve a POST to /definitions so the fix for #604 doesn't cover it (although I suspect there is also a bug there as well). I was able to reproduce this problem just by directly navigating to a definitions page using casing that differs from what is stored. For example making a curation at `https://dev.clearlydefined.io/definitions/pypi/pypi/-/Pillow/6.0.0` will trigger the bug. `Pillow` should be `pillow`

To fix the issue I'm thinking we should do two things to keep things clean long term. 1. not serve up definitions with a case different from what we store internally. For example, if the user directly accesses `/definitions/npm/npmjs/-/Babel-runtime/6.26.0` we should redirect them to `/definitions/npm/npmjs/-/babel-runtime/6.26.0` (lower case babel is what we store internally). 2. the curation API itself should either not accept mismatched case or should do normalization when a curation is submitted. If we do 1 then it shouldn't be a problem, I think, to just reject mismatched casing and that seems cleanest to me. Done this way users of the website shouldn't have to pay attention and it should just work cleanly.

Fixing the curation could involve modifying `providers/curation/github.js` `addOrUpdate` or `_validateDefinitionsExist`.

**Comment by nellshamrell** [comment]
I think this may have been fixed at some point.

If I use an upper case C and navigate to [Css-what](https://clearlydefined.io/definitions/npm/npmjs/-/Css-what/1.0.0)

I appear to be auto-redirected to the definition for [css-what](https://clearlydefined.io/definitions/npm/npmjs/-/css-what/1.0.0).

I see the same curations listed at both URLs.

If anyone sees this issue again, please feel free to re-open!
