### ISSUE TITLE
Merged PRs not updating the definition 

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#705]
For all of these components, there is a merged PR that updated the declared license, however the declared license was not actually updated on the definition.  

•	nuget/nuget/-/dotnetty.codecs.mqtt/0.4.6 - https://github.com/clearlydefined/curated-data/pull/3516 - PR shows merged (MIT)
•	nuget/nuget/-/microsoft.azure.amqp/2.3.6 - https://github.com/clearlydefined/curated-data/pull/3515 - PR shows merged (MIT)
•	nuget/nuget/-/microsoft.azure.devices.client/1.6.0 - https://github.com/clearlydefined/curated-data/pull/3522/files  - PR shows merged (MIT)
•	nuget/nuget/-/microsoft.azure.devices.shared/1.5.0 - https://github.com/clearlydefined/curated-data/pull/3517/files - PR shows merged (MIT)
•	nuget/nuget/-/microsoft.azure.devices/1.6.0 - https://github.com/clearlydefined/curated-data/pull/3518/files - PR shows merged (MIT)
•	nuget/nuget/-/microsoft.azure.management.hdinsight/1.0.13-preview - https://github.com/clearlydefined/curated-data/pull/3526/files - PR shows merged (MIT)
•	nuget/nuget/-/microsoft.codeanalysis.binskim/1.3.6 - https://github.com/clearlydefined/curated-data/pull/3519/files - PR shows merged (MIT)
•	nuget/nuget/-/microsoft.windowsazure.sdk/2.9.0 - https://github.com/clearlydefined/curated-data/pull/3529/files - PR shows merged (NONE)
•	nuget/nuget/-/mono.security/3.2.3 - https://github.com/clearlydefined/curated-data/pull/3528/files - PR shows merged (MIT)
•	nuget/nuget/-/razorengine/3.7.2 https://github.com/clearlydefined/curated-data/pull/3521/files - PR shows merged (Apache-2.0)

@geneh , @fossygirl

**Comment by geneh** [comment]
It looks like https://clearlydefined.io/definitions/nuget/nuget/-/DotNetty.Codecs.Mqtt/0.4.6 was curated on Feb 12th and the definition was updated at 2020-02-12T12:40:49.685Z as expected. In fact, there were two curations:
https://github.com/clearlydefined/curated-data/pull/3514
https://github.com/clearlydefined/curated-data/pull/3516
It needs to be investigated why the license wasn't updated to MIT one as expected by updateContribution method.

**Comment by ariel11** [comment]
Yes, right - there are "merged" PRs updating the "Declared" license, but when you open the component definition, it still says NOASSERTION (on all of the ones in my list above).

![image](https://user-images.githubusercontent.com/17935946/74595799-db6d1980-4ffa-11ea-81ea-bb1e59efc89e.png)

**Comment by geneh** [comment]
An observation: all these components do not have curation tool run, need to figure out why.

**Comment by geneh** [comment]
I have corrected the first two components https://clearlydefined.io/definitions/nuget/nuget/-/DotNetty.Codecs.Mqtt/0.4.6 & https://clearlydefined.io/definitions/nuget/nuget/-/Microsoft.Azure.Amqp/2.3.6, will correct the rest tomorrow.

This is a component name casing issue. Until the issue is fully fixed, please make sure to load the components using the right casing, e.g. https://clearlydefined.io/definitions/nuget/nuget/-/DotNetty.Codecs.Mqtt/0.4.6 and not https://clearlydefined.io/definitions/nuget/nuget/-/dotnetty.codecs.mqtt/0.4.6. Otherwise, PRs with the wrong yaml file casing are opened which cause this problem.

Workaround steps taken:
1. Update the curated file with the right casing, e.g. https://github.com/clearlydefined/curated-data/blob/master/curations/nuget/nuget/-/Microsoft.Azure.Amqp.yaml
2. Delete the incorrectly created curation file, e.g. https://github.com/clearlydefined/curated-data/blob/master/curations/nuget/nuget/-/microsoft.azure.amqp.yaml
3. Trigger component re-compute either through harvests queue or /webhook API, e.g.
```
{
    "_metadata": {
        "links": {
            "self": {
                "href": "urn:nuget:nuget:-:DotNetty.Codecs.Mqtt:revision:0.4.6"
            }
        }
    }
}
```

**Comment by geneh** [comment]
This issue has been resolved and the data corrected.
