### ISSUE TITLE
Search Index is broken

### ISSUE THREAD

**Issue by jcfiorenzano** [clearlydefined/service#712]
We are having problems indexing a property that is not coming in all documents.

localId=https%3a%2f%2fclearlydefineddev.blob.core.windows.net%2fdevelop-definition%2fcomposer%2fpackagist%2fmediadevs%2fform-assist%2frevision%2f1.0.0.json&documentKey=https%3a%2f%2fclearlydefineddev.blob.core.windows.net%2fdevelop-definition%2fcomposer%2fpackagist%2fmediadevs%2fform-assist%2frevision%2f1.0.0.json

**Comment by geneh** [comment]
Operation: DocumentExtraction.azureblob.definitionsdatasource
Message: Could not parse document. Cannot find token 'projectWebsite' in path '/described/projectWebsite'

A ticket should be opened to Azure Search Services since it shouldn't fail to index a JSON blob for optionally missing keys.
In the meantime as a workaround, it should be evaluated whether all such optional fields, e.g. projectWebsite, issueTracker etc., can safely be removed from the indexer.
AzureSearch class currently exposes only two methods: suggestCoordinates and query.
suggestCoordinates doesn't use these optional fields. The query method is only used by the StatsService class and and it doesn't seem to use these optional fields as well.
Thus, I suggest removing or commenting out the optional fields from AzureSearch _buildDefinitionsIndex and _buildIndexer methods.

**Comment by jcfiorenzano** [comment]
A support request was open the id is 120031021002123 https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/managesupportrequest

The Fields that are having problems are:

- /described/projectWebsite
- /described/issueTracker
- /described/files
- /described/sourceLocation/url
- /described/releaseDate
- /licensed/facets/core/discovered/expressions
- /licensed/facets/core/attribution/parties
- /licensed/declared
- /coordinates/namespace

**Comment by geneh** [comment]
Perfect, thanks! I think we probably can't drop /licensed/declared and /coordinates/namespace from indexing, so will need to wait until the issue gets resolved.

**Comment by nellshamrell** [comment]
@jcfiorenzano @geneh was this ever resolved?

**Comment by nellshamrell** [comment]
Haven't heard back, going to close this for now, but if someone sees this again or has more information please feel free to re-open.
