### ISSUE TITLE
Store JSON files in a database, not in the filesystem 

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/service#750]
As a follow up to #386 there are serious issues with the way all data is stored in a filesystem (aka. Azure blob store). The problem is simple: 50 millions of JSON files in deeply nested directory tree of 50 millions directory makes every filesystem balk, unless you use some cloud storage which should not be a mandated requirement.  This makes alternative installations of ClearlyDefined almost impossible unless you deploy significant infrastructure which is not specifically needed. I also suspect that since iterating Azure blob store seems rather slow, this may be the cause of further Clouflare timeouts such as in #749  

In https://github.com/nexB/clearcode-toolkit/ we use a very simple database storage (which could be improved alright) using PostgreSQL (but any relational database would do) with two columns one for path and one for data: we store a path as a key and the JSON as data and this scales nicely and without problem to millions of records on a small machine. Further more it is much faster to access and takes less space on disk as the filesystem metadata overhead is rather significant at that scale.

Therefore, I think we should consider using a plain database for storage instead of the Azure blob store or a plain filesystem with the following benefits:
- less storage
- faster access
- easier mirroring 
- no cloud infrastructure dependency

**Comment by nellshamrell** [comment]
We discussed this at Monday's community meeting.

The reason we store the data in blob storage is because it is cheap and fast to serve up. I'm separately checking on our storage to see if it is slow for some reason. We don't currently see a compelling reason to switch from blob storage to another storage mechanism at this time (though, should someone want an alternative to Azure blobs like AWS S3, they can write an adapter for that provider). So I am closing this, but we can re-open if needed.
